In [1]:
import pandas as pd
import requests

In [2]:
response=requests.get('https://api.cricapi.com/v1/currentMatches?apikey=caf841d2-bf2f-483b-ad04-c7bc46840500&offset=0')

In [3]:
df=pd.DataFrame(response.json()['data'])

In [4]:
df

,id,name,status,venue,date,dateTimeGMT,teams,teamInfo,score,series_id,fantasyEnabled,bbbEnabled,hasSquad,matchStarted,matchEnded,matchType
0,5d4505eb-8d9c-4afa-ab8d-5dd7316ee568,"Kent vs Nottinghamshire, Group A",Nottinghamshire won by 1 wkt,"St Lawrence Ground, Canterbury",2023-08-17,2023-08-17T10:00:00,"[Kent, Nottinghamshire]","[{'name': 'Kent', 'shortname': 'KENT', 'img': ...","[{'r': 259, 'w': 9, 'o': 50, 'inning': 'Kent I...",56227d4f-de98-4a7a-a716-12066ac48033,True,False,True,True,True,NaN
1,f547eb1b-6555-462b-bcbd-0c4e6c46555f,"Durham vs Somerset, Group B",Somerset won by 6 wkts,"Roseworth Terrace, Gosforth",2023-08-17,2023-08-17T10:00:00,"[Durham, Somerset]","[{'name': 'Durham', 'shortname': 'DURH', 'img'...","[{'r': 181, 'w': 10, 'o': 45, 'inning': 'Durha...",56227d4f-de98-4a7a-a716-12066ac48033,True,False,True,True,True,NaN
2,a2d8f1f2-a7c1-4eca-a530-89e5bb322cb9,"Surrey vs Lancashire, Group A",Lancashire won by 10 wkts,"Woodbridge Road, Guildford",2023-08-17,2023-08-17T10:00:00,"[Surrey, Lancashire]","[{'name': 'Lancashire', 'shortname': 'LNCS', '...","[{'r': 153, 'w': 10, 'o': 37.3, 'inning': 'Sur...",56227d4f-de98-4a7a-a716-12066ac48033,True,False,True,True,True,NaN
3,a819b2ec-0d38-4a4f-9912-411fff9bee8f,"Yorkshire vs Hampshire, Group A",Hampshire won by 177 runs,"York Cricket Club, York",2023-08-17,2023-08-17T10:00:00,"[Yorkshire, Hampshire]","[{'name': 'Hampshire', 'shortname': 'HAM', 'im...","[{'r': 311, 'w': 6, 'o': 50, 'inning': 'Hampsh...",56227d4f-de98-4a7a-a716-12066ac48033,True,False,True,True,True,NaN
4,164390d0-6cdf-47cd-a386-e83d1bd5be34,"B-Love Kandy vs Jaffna Kings, Eliminator",B - Love Kandy won by 61 runs,"R.Premadasa Stadium, Colombo",2023-08-17,2023-08-17T14:00:00,"[B-Love Kandy, Jaffna Kings]","[{'name': 'B-Love Kandy', 'shortname': 'BK', '...","[{'r': 188, 'w': 8, 'o': 20, 'inning': 'B-Love...",4d9cfae4-e921-4b3e-89ff-368d5ec83a3a,True,True,True,True,True,t20
5,06e866a1-3349-47f6-93f1-4467336dba13,"Dambulla Aura vs Galle Titans, Qualifier 1",Dambulla Aura won by 6 wkts,"R.Premadasa Stadium, Colombo",2023-08-17,2023-08-17T09:30:00,"[Dambulla Aura, Galle Titans]","[{'name': 'Dambulla Aura', 'shortname': 'DA', ...","[{'r': 146, 'w': 10, 'o': 20, 'inning': 'Galle...",4d9cfae4-e921-4b3e-89ff-368d5ec83a3a,True,True,True,True,True,t20
6,5cbb81c7-6d6d-41a0-b92b-f8d9fc31af67,"Mangalore Dragons vs Hubli Tigers, 10th Match",Hubli Tigers won by 63 runs,"M.Chinnaswamy Stadium, Bengaluru",2023-08-17,2023-08-17T11:30:00,"[Mangalore Dragons, Hubli Tigers]","[{'name': 'Hubli Tigers', 'shortname': 'HT', '...","[{'r': 215, 'w': 5, 'o': 20, 'inning': 'Hubli ...",9a2f9196-a26c-40c3-b9f6-663babd0c8a2,True,True,True,True,True,t20
7,1380aef9-13bd-4f7f-99fa-7e9c4ed5d96d,"Gulbarga Mystics vs Shivamogga Lions, 9th Match",Shivamogga Lions won by 3 wkts,"M.Chinnaswamy Stadium, Bengaluru",2023-08-17,2023-08-17T07:30:00,"[Gulbarga Mystics, Shivamogga Lions]","[{'name': 'Gulbarga Mystics', 'shortname': 'GU...","[{'r': 175, 'w': 6, 'o': 20, 'inning': 'Gulbar...",9a2f9196-a26c-40c3-b9f6-663babd0c8a2,True,True,True,True,True,t20
8,794bdf0d-8b1b-4c10-9857-88b9c792e354,"Saint Lucia Kings vs Jamaica Tallawahs, 1st Match",Jamaica Tallawahs won by 11 runs,"Daren Sammy National Cricket Stadium, Gros Isl...",2023-08-16,2023-08-16T23:00:00,"[Saint Lucia Kings, Jamaica Tallawahs]","[{'name': 'Jamaica Tallawahs', 'shortname': 'J...","[{'r': 187, 'w': 10, 'o': 20, 'inning': 'Jamai...",830af3da-5a0b-4b83-8d73-9800089be118,True,True,True,True,True,t20
9,22455f04-df0f-4917-8d04-4a7bccfbc348,"Netherlands Women vs Ireland Women, 3rd T20I",Ireland Women won by 6 wkts,"VRA Cricket Ground, Amstelveen",2023-08-17,2023-08-17T10:00:00,"[Netherlands Women, Ireland Women]","[{'name': 'Ireland Women', 'shortname': 'IRW',...","[{'r': 116, 'w': 6, 'o': 20, 'inning': 'Nether...",45809f27-e5d4-4952-9463-a61d2360d492,True,True,True,True,True,t20
10,4211d6d0-2339-44dc-99de-304b54ca1bd2,"United Arab Emirates vs New Zealand, 1st T20I",New Zealand won by 19 runs,"Dubai International Cricket Stadium, Dubai",2023-08-17,2023-08-17T14:00:00,"[United Arab Emirates, New Zealand]","[{'name': 'New Zealand', 'shortname': 'NZ', 'i...","[{'r': 155, 'w': 6, 'o': 20, 'inning': 'United...",7502fafa-6f5a-4841-ba9a-0ef80dc5e5f6,True,True,True,True,True,t20
11,05a8e6cc-41e8-4c17-bcbd-fe1a29509baf,Trent Rockets Women vs Manchester Originals Wo...,Trent Rockets Women won by 9 wkts,"Trent Bridge, Nottingham",2023-08-17,2023-08-17T14:00:00,"[Trent Rockets Women, Manchester Originals Women]","[{'name': 'Manchester Originals Women', 'short...","[{'r': 107, 'w': 5, 'o': 100, 'inning': 'Manch...",034204b0-5379-4856-88bb-dbdcd94fda3a,True,False,True,True,True,NaN
12,f58b1628-a5bc-4788-aab4-b8494abb5edc,"Trent Rockets vs Manchester Originals, 23rd Match",Manchester Originals won by 10 runs,"Trent Bridge, Nottingham",2023-08-17,2023-08-17T17:30:00,"[Trent Rockets, Manchester Originals]","[{'name': 'Manchester Originals', 'shortname':...","[{'r': 181, 'w': 6, 'o': 100, 'inning': 'Manch...",78373c2a-5f35-4287-a155-a51e3f8572ff,True,False,True,True,True,NaN

In [5]:
df.shape

(13, 16)

In [6]:
dff=df.iloc[:,0:10]

In [7]:
dff

,id,name,status,venue,date,dateTimeGMT,teams,teamInfo,score,series_id
0,5d4505eb-8d9c-4afa-ab8d-5dd7316ee568,"Kent vs Nottinghamshire, Group A",Nottinghamshire won by 1 wkt,"St Lawrence Ground, Canterbury",2023-08-17,2023-08-17T10:00:00,"[Kent, Nottinghamshire]","[{'name': 'Kent', 'shortname': 'KENT', 'img': ...","[{'r': 259, 'w': 9, 'o': 50, 'inning': 'Kent I...",56227d4f-de98-4a7a-a716-12066ac48033
1,f547eb1b-6555-462b-bcbd-0c4e6c46555f,"Durham vs Somerset, Group B",Somerset won by 6 wkts,"Roseworth Terrace, Gosforth",2023-08-17,2023-08-17T10:00:00,"[Durham, Somerset]","[{'name': 'Durham', 'shortname': 'DURH', 'img'...","[{'r': 181, 'w': 10, 'o': 45, 'inning': 'Durha...",56227d4f-de98-4a7a-a716-12066ac48033
2,a2d8f1f2-a7c1-4eca-a530-89e5bb322cb9,"Surrey vs Lancashire, Group A",Lancashire won by 10 wkts,"Woodbridge Road, Guildford",2023-08-17,2023-08-17T10:00:00,"[Surrey, Lancashire]","[{'name': 'Lancashire', 'shortname': 'LNCS', '...","[{'r': 153, 'w': 10, 'o': 37.3, 'inning': 'Sur...",56227d4f-de98-4a7a-a716-12066ac48033
3,a819b2ec-0d38-4a4f-9912-411fff9bee8f,"Yorkshire vs Hampshire, Group A",Hampshire won by 177 runs,"York Cricket Club, York",2023-08-17,2023-08-17T10:00:00,"[Yorkshire, Hampshire]","[{'name': 'Hampshire', 'shortname': 'HAM', 'im...","[{'r': 311, 'w': 6, 'o': 50, 'inning': 'Hampsh...",56227d4f-de98-4a7a-a716-12066ac48033
4,164390d0-6cdf-47cd-a386-e83d1bd5be34,"B-Love Kandy vs Jaffna Kings, Eliminator",B - Love Kandy won by 61 runs,"R.Premadasa Stadium, Colombo",2023-08-17,2023-08-17T14:00:00,"[B-Love Kandy, Jaffna Kings]","[{'name': 'B-Love Kandy', 'shortname': 'BK', '...","[{'r': 188, 'w': 8, 'o': 20, 'inning': 'B-Love...",4d9cfae4-e921-4b3e-89ff-368d5ec83a3a
5,06e866a1-3349-47f6-93f1-4467336dba13,"Dambulla Aura vs Galle Titans, Qualifier 1",Dambulla Aura won by 6 wkts,"R.Premadasa Stadium, Colombo",2023-08-17,2023-08-17T09:30:00,"[Dambulla Aura, Galle Titans]","[{'name': 'Dambulla Aura', 'shortname': 'DA', ...","[{'r': 146, 'w': 10, 'o': 20, 'inning': 'Galle...",4d9cfae4-e921-4b3e-89ff-368d5ec83a3a
6,5cbb81c7-6d6d-41a0-b92b-f8d9fc31af67,"Mangalore Dragons vs Hubli Tigers, 10th Match",Hubli Tigers won by 63 runs,"M.Chinnaswamy Stadium, Bengaluru",2023-08-17,2023-08-17T11:30:00,"[Mangalore Dragons, Hubli Tigers]","[{'name': 'Hubli Tigers', 'shortname': 'HT', '...","[{'r': 215, 'w': 5, 'o': 20, 'inning': 'Hubli ...",9a2f9196-a26c-40c3-b9f6-663babd0c8a2
7,1380aef9-13bd-4f7f-99fa-7e9c4ed5d96d,"Gulbarga Mystics vs Shivamogga Lions, 9th Match",Shivamogga Lions won by 3 wkts,"M.Chinnaswamy Stadium, Bengaluru",2023-08-17,2023-08-17T07:30:00,"[Gulbarga Mystics, Shivamogga Lions]","[{'name': 'Gulbarga Mystics', 'shortname': 'GU...","[{'r': 175, 'w': 6, 'o': 20, 'inning': 'Gulbar...",9a2f9196-a26c-40c3-b9f6-663babd0c8a2
8,794bdf0d-8b1b-4c10-9857-88b9c792e354,"Saint Lucia Kings vs Jamaica Tallawahs, 1st Match",Jamaica Tallawahs won by 11 runs,"Daren Sammy National Cricket Stadium, Gros Isl...",2023-08-16,2023-08-16T23:00:00,"[Saint Lucia Kings, Jamaica Tallawahs]","[{'name': 'Jamaica Tallawahs', 'shortname': 'J...","[{'r': 187, 'w': 10, 'o': 20, 'inning': 'Jamai...",830af3da-5a0b-4b83-8d73-9800089be118
9,22455f04-df0f-4917-8d04-4a7bccfbc348,"Netherlands Women vs Ireland Women, 3rd T20I",Ireland Women won by 6 wkts,"VRA Cricket Ground, Amstelveen",2023-08-17,2023-08-17T10:00:00,"[Netherlands Women, Ireland Women]","[{'name': 'Ireland Women', 'shortname': 'IRW',...","[{'r': 116, 'w': 6, 'o': 20, 'inning': 'Nether...",45809f27-e5d4-4952-9463-a61d2360d492
10,4211d6d0-2339-44dc-99de-304b54ca1bd2,"United Arab Emirates vs New Zealand, 1st T20I",New Zealand won by 19 runs,"Dubai International Cricket Stadium, Dubai",2023-08-17,2023-08-17T14:00:00,"[United Arab Emirates, New Zealand]","[{'name': 'New Zealand', 'shortname': 'NZ', 'i...","[{'r': 155, 'w': 6, 'o': 20, 'inning': 'United...",7502fafa-6f5a-4841-ba9a-0ef80dc5e5f6
11,05a8e6cc-41e8-4c17-bcbd-fe1a29509baf,Trent Rockets Women vs Manchester Originals Wo...,Trent Rockets Women won by 9 wkts,"Trent Bridge, Nottingham",2023-08-17,2023-08-17T14:00:00,"[Trent Rockets Women, Manchester Originals Women]","[{'name': 'Manchester Originals Women', 'short...","[{'r': 107, 'w': 5, 'o': 100, 'inning': 'Manch...",034204b0-5379-4856-88bb-dbdcd94fda3a
12,f58b1628-a5bc-4788-aab4-b8494abb5edc,"Trent Rockets vs Manchester Originals, 23rd Match",Manchester Originals won by 10 runs,"Trent Bridge, Nottingham",2023-08-17,2023-08-17T17:30:00,"[Trent Rockets, Manchester Originals]","[{'name': 'Manchester Originals', 'shortname':...","[{'r': 181, 'w': 6, 'o': 100, 'inning': 'Manch...",78373c2a-5f35-4287-a155-a51e3f8572ff